<?php

namespace Rs\CollezioneStronatiBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProduttoreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduttoreRepository extends EntityRepository
{
    public function findProduttoriPerOggetto($classeOggetto) {

        $em = $this->getEntityManager ();

        $dql = "SELECT DISTINCT produttore FROM RsCollezioneStronatiBundle:Produttore produttore";
        $dql .= " INNER JOIN produttore.oggetto oggetto";
        $dql .= " WHERE oggetto INSTANCE OF ".$classeOggetto;
        $dql .= " ORDER BY produttore.nome ASC";
        $queryIdratata = $em->createQuery ( $dql );
        return $queryIdratata->getResult ();
    }
}
