<?php

namespace Rs\ImportazioneBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * OldBicchiereRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OldBicchiereRepository extends EntityRepository
{

    public function getProduttoriDistinct(){

        $dql = "SELECT DISTINCT b.ditta FROM RsImportazioneBundle:OldBicchiere b";
        $queryIdratata = $this->getEntityManager()->createQuery ( $dql );
        return $queryIdratata->getResult();
    }

    public function findAllLimitato($nElementi){
        return $this->getEntityManager()->createQuery("SELECT b FROM RsImportazioneBundle:OldBicchiere b")->setMaxResults($nElementi)->getResult();
    }
}
