<?php

namespace Rs\ImportazioneBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * OldMignonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OldMignonRepository extends EntityRepository
{
    public function getProduttoriDistinct(){

        $dql = "SELECT DISTINCT b.produttore FROM RsImportazioneBundle:OldMignon b";
        $queryIdratata = $this->getEntityManager()->createQuery ( $dql );
        return $queryIdratata->getResult();
    }

    public function findAllLimitato($nElementi){
        return $this->getEntityManager()->createQuery("SELECT m FROM RsImportazioneBundle:OldMignon m")->setMaxResults($nElementi)->getResult();
    }
}
