<?php

namespace Rs\ImportazioneBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * OldProfumoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OldProfumoRepository extends EntityRepository
{
    public function getProduttoriDistinct(){

        $dql = "SELECT DISTINCT b.produttore FROM RsImportazioneBundle:OldProfumo b";
        $queryIdratata = $this->getEntityManager()->createQuery ( $dql );
        return $queryIdratata->getResult();
    }

    public function findAllLimitato($nElementi){
        return $this->getEntityManager()->createQuery("SELECT p FROM RsImportazioneBundle:OldProfumo p")->setMaxResults($nElementi)->getResult();
    }
}
