security:
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                login_path: /login
                always_use_default_target_path: true
                default_target_path: /home
            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: ROLE_ADMIN }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/_wdt, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/mignon/elenco, role: ROLE_VISUALIZZATORE_MIGNON }
        - { path: ^/mignon/mostra, role: ROLE_VISUALIZZATORE_MIGNON }
        - { path: ^/mignon, role: ROLE_EDITORE }
        - { path: ^/bicchiere/elenco, role: ROLE_VISUALIZZATORE_BICCHIERI }
        - { path: ^/bicchiere/mostra, role: ROLE_VISUALIZZATORE_BICCHIERI }
        - { path: ^/bicchiere, role: ROLE_EDITORE }
        - { path: ^/profumo/elenco, role: ROLE_VISUALIZZATORE_PROFUMI }
        - { path: ^/profumo/mostra, role: ROLE_VISUALIZZATORE_PROFUMI }
        - { path: ^/profumo, role: ROLE_EDITORE }
        - { path: ^/oggetti, role: ROLE_EDITORE }
        - { path: ^/produttore, role: ROLE_EDITORE }
        - { path: ^/sincronizza, role: ROLE_SINCRONIZZATORE }
        - { path: ^/importazione, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, role: ROLE_USER }

    role_hierarchy:
        ROLE_VISUALIZZATORE_MIGNON: ROLE_USER
        ROLE_VISUALIZZATORE_PROFUMI: ROLE_USER
        ROLE_VISUALIZZATORE_BICCHIERI: ROLE_USER
        ROLE_VISUALIZZATORE: [ROLE_VISUALIZZATORE_MIGNON, ROLE_VISUALIZZATORE_PROFUMI,ROLE_VISUALIZZATORE_BICCHIERI]
        ROLE_SINCRONIZZATORE: ROLE_USER
        ROLE_EDITORE:     ROLE_VISUALIZZATORE
        ROLE_ADMIN:       ROLE_EDITORE
        ROLE_SUPER_ADMIN: ROLE_ADMIN